name: Automated Build

on:
  push: # main 브랜치에 Push가 되면 빌드가 되도록 동작시킵니다.
    branches: [ main ]
    
jobs:
  buildAndroid:
    name: Android Build
    runs-on: ubuntu-latest
    
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      # 캐시파일을 생성하여 다음 빌드시 더 빠르게 빌드를 할 수 있도록 해줍니다.
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ runner.os }}-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-${{ runner.os }}-
            Library-

      # Android SDK 설정
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Build
      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: Android
          buildName: UnityBuild
          androidExportType: androidPackage # APK 빌드

      # Output
      - uses: actions/upload-artifact@v4
        with:
          name: UnityBuild-Android
          path: build
